[package]
name = "rust_2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
fxhash = "0.2.1"
xxhash-rust = "0.8.2"
nohash-hasher = "0.2.0"
md5 = "0.7.0"
rust-crypto = "0.2.36"